before:
  hooks:
    - go mod download
builds:
- goos:
    - darwin
    - linux
  goarch:
    - amd64
  main: main.go
brews:
  - description: "ecs-service-logs is used to filter JSON-formatted log lines in CloudWatch."
    github:
      owner: trussworks
      name: homebrew-tap
    homepage: "https://github.com/trussworks/ecs-service-logs"
    commit_author:
      name: trussworks-infra
      email: infra+github@truss.works
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
