env:
  - GO111MODULE=auto
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    main: main.go
brews:
  - description: "ecs-service-logs is used to filter JSON-formatted log lines in CloudWatch."
    tap:
      owner: trussworks
      name: homebrew-tap
    homepage: "https://github.com/trussworks/ecs-service-logs"
    commit_author:
      name: trussworks-infra
      email: infra+github@truss.works
dockers:
  - ids:
      - ecs-service-logs
    image_templates:
      - "trussworks/ecs-service-logs:{{ .Tag }}"
    skip_push: true
archives:
  - id: foo
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: "checksums.txt"
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
