repos:
  - repo: git://github.com/golangci/golangci-lint
    rev: v1.28.2
    hooks:
      - id: golangci-lint

  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: trailing-whitespace

  - repo: git://github.com/igorshubovych/markdownlint-cli
    rev: v0.23.2
    hooks:
      - id: markdownlint

  - repo: git://github.com/trussworks/pre-commit-hooks
    rev: v0.0.4
    hooks:
      - id: circleci-validate
      - id: goreleaser-check
