references:
  circleci: &circleci trussworks/circleci:29ab89fdada1f85c5d8fb685a2c71660f0c5f60c

jobs:
  release:
    docker:
    - auth:
        password: $DOCKER_PASSWORD
        username: $DOCKER_USERNAME
      image: *circleci
    steps:
    - checkout
    - setup_remote_docker
    - run: goreleaser
    - run:
        command: docker login -u $DOCKER_USER -p $DOCKER_PASS
        name: Login to Docker Hub
    - run:
        command: docker run -it trussworks/ecs-service-logs:<< pipeline.git.tag >>
          --help
        name: Test that Docker container works
    - run:
        command: docker push trussworks/ecs-service-logs:<< pipeline.git.tag >>
        name: Docker push
  validate:
    docker:
    - auth:
        password: $DOCKER_PASSWORD
        username: $DOCKER_USERNAME
      image: *circleci
    steps:
    - checkout
    - restore_cache:
        keys:
        - pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
        - go-mod-sources-v1-{{ checksum "go.sum" }}
    - run:
        command: pre-commit run --all-files
        name: Run pre-commit tests
    - run:
        command: make test
        name: Run Go tests
    - save_cache:
        key: pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
        paths:
        - ~/.cache/pre-commit
    - save_cache:
        key: go-mod-sources-v1-{{ checksum "go.sum" }}
        paths:
        - ~/go/pkg/mod
version: 2.1
workflows:
  release:
    jobs:
    - release:
        filters:
          branches:
            ignore: /^.*/
          tags:
            only: /^v[0-9]+(\.[0-9]+)*(-.*)*/
  validate:
    jobs:
    - validate:
        context:
        - org-global
  version: 2.1
